# Generated by Django 2.0.3 on 2018-03-21 10:59

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=about.models.upload_to),
        ),
    ]
